### ISSUE TITLE
Multiple inheritance between RandomVariable and tf.contrib.distributions.Distribution no longer works

### ISSUE THREAD

**Issue by shoyer** [blei-lab/edward#363]
With the latest TensorFlow, attempting to import Edwards yields errors like:
`First parent class declared for Empirical must be Distribution, but saw: RandomVariable`

It looks like this was broken by @ebrevdo's change  https://github.com/tensorflow/tensorflow/commit/3cb343915a9726b943d2fbb45e26148e9b83fa0e

It's not obvious to me whether the right fix here is in Edward or upstream in TensorFlow but I thought I would point this out, if you hadn't noticed already.

For what it's worth, my guess is that it would probably be more reliable to use composition rather than inheritance for `RandomVariable`.

**Comment by shoyer** [comment]
Oops, this is a dupe of https://github.com/blei-lab/edward/issues/363!

**Comment by dustinvtran** [comment]
#315 Thanks for the heads-up. I guess this happens in the TensorFlow's 0.12.0rc0 release?

**Comment by shoyer** [comment]
Yes, though I think this is also present in 0.11.

**Comment by dustinvtran** [comment]
Good to know. I asked @ebrevdo about this a few weeks ago. I added an issue to Github (#5930).

**Comment by ebrevdo** [comment]
I thought we fixed this.  Might have to double check.

**Comment by rw** [comment]
This is not fixed. With Tensorflow 0.12.0rc0 and Edward commit 241ede722095cbab0fee6a3af58c589d1ae90eff (master as of today) I get:

```
TypeError: First parent class declared for Empirical must be Distribution, but saw 'RandomVariable'
```

**Comment by ebrevdo** [comment]
I'm pushing a fix soon.  It'll show up in tf master branch, not in the
r0.12 release.

**Comment by rw** [comment]
@ebrevdo Do you have a suggestion for a workaround? I'm just beginning to learn `edward` so I am hoping to get a hello world working soon.

**Comment by rw** [comment]
Installing Tensorflow 0.11.0 got it working for me. I had to get the wheel from the Tensorflow homepage, because old versions don't exist in `pip` anymore (groan).

**Comment by dustinvtran** [comment]
thanks @ebrevdo! 

@rw: as you mentioned, for now it makes sense to work with tensorflow 0.11.0. i'll see if i can do a hot fix that will get edward working with the tensorflow 0.12 release.
